export const SET_TOPICS_TAB = 'SET_TOPICS_TAB'
export const SET_TOPICS_LOADING = 'SET_TOPICS_LOADING'
export const SET_TOPICS_LIST = 'SET_TOPICS_LIST';
export const SET_TOPICS_INIT = 'SET_TOPICS_INIT';